services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - mysql_pass
      - wp_a_pass
      - wp_user_pass
    restart: on-failure
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - mysql_pass
    restart: on-failure

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/Users/eperperi/data/database"
  web:
    name: web
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/Users/eperperi/data/web"

networks:
    inception:
      driver: bridge

secrets:
  mysql_pass:
    file: ../secrets/credentials.txt
  wp_a_pass:
    file: ../secrets/db_root_password.txt
  wp_user_pass:
    file: ../secrets/db_password.txt