FROM debian:latest

# ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y &&  apt-get install -y \
	 mariadb-server

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/.
COPY init.sql /etc/mysql/init.sql

RUN mkdir /run/mysqld

CMD ["mysqld_safe"]