services:
  nginx:
    build: nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  wordpress:
    build: wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  mariadb:
    build: mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/eperperi/data/database"
  web:
    name: web
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "/home/eperperi/data/web"

networks:
    inception:
      driver: bridge